### ISSUE TITLE
composer require t1st3/php-json-minify

### ISSUE THREAD

**Issue by ivantcholakov** [t1st3/php-json-minify#1]
Why composer installs so many dependencies just for using a 129-lines script?

**Comment by t1st3** [comment]
Hi there,
sorry for the delay with this. Sure, there are too many useless dependencies in composer.json. I think these deps were actually dev-dependencies (and you can see most of theme are duplicated in dependencies AND in dev-dependencies).
I'll correct this problem hopefully by the end of the week.
Thanks for submitting this issue.

**Comment by t1st3** [comment]
Fixed in 0.4.0 .
Thanks
